# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfed884e79c93fd787483fa50c9cb69fdb60b3e8398addfe7306be7a2d611bb0f0e4dc0d012872f67b57e93b844f090b6d06abf0e1ab93b4f5ea1f0b2c4ba625

test:
  secret_key_base: a0ece1c67c011799f2df9b927be63625dc349b99aa667c79c961f347896c74893a724d6a3a15378f66864bb1ac6d5418a329e815f3b0854cd5740bbff0c39b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
